---

branches:
  only:
    - "master"
    - "molecule-test-harness"

dist: bionic

language: python
python: 3.5

env:
  matrix:
    - MOLECULE_DISTRO: centos/7
    - MOLECULE_DISTRO: centos/8
    - MOLECULE_DISTRO: debian/jessie64
    - MOLECULE_DISTRO: debian/stretch64
    - MOLECULE_DISTRO: debian/buster64
    - MOLECULE_DISTRO: generic/ubuntu1604
    - MOLECULE_DISTRO: generic/ubuntu1804


install:
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  - sudo dpkg -i vagrant_2.2.7_x86_64.deb
  - vagrant --version

  - sudo vagrant plugin install vagrant-libvirt

  - pip3 install molecule yamllint ansible-lint python-vagrant molecule-vagrant


script:
  - molecule test
