---

branches:
  only:
    - "master"

dist: focal

language: python
python: 3.8

addons:
  apt:
    packages:
      - python3-pip
      - libssl-dev
      - python3-virtualenv
      - ruby-libvirt
      - qemu
      - libvirt-daemon-system
      - libvirt-clients
      - libxslt-dev
      - libxml2-dev
      - libvirt-dev
      - zlib1g-dev
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - libvirt-dev
      - qemu-kvm
      - qemu-utils
      - ruby-dev
    update: true

env:
  matrix:
    - MOLECULE_DISTRO: centos/7
    - MOLECULE_DISTRO: centos/8
    - MOLECULE_DISTRO: debian/stretch64
    - MOLECULE_DISTRO: debian/buster64
    - MOLECULE_DISTRO: generic/ubuntu1604
    - MOLECULE_DISTRO: generic/ubuntu1804
    - MOLECULE_DISTRO: generic/ubuntu2004

before_install:
  - wget https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - rm chromedriver_linux64.zip

install:
  - |
    export VAGRANT_VERSION=2.2.10
    sudo wget -nv https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
    sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
    vagrant --version
  - sudo vagrant plugin install vagrant-libvirt
  - pip3 install molecule yamllint ansible-lint python-vagrant molecule-vagrant "molecule[lint]" testinfra selenium
  - sudo chown -R travis:travis /home/travis/.vagrant.d
  - sudo gpasswd -a travis libvirt

script:
  - travis_retry sudo -E su travis -c "source $VIRTUAL_ENV/bin/activate; molecule create && molecule converge && TEST && molecule destroy"
