---

- name: "Check for supported distribution"
  fail:
    msg: "Distro {{ ansible_distribution }} is not supported yet."
  when: ansible_os_family not in graylog_supported_os_families

- name: "Check required variables"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ required_vars }}"
  tags: configuration

- include_tasks: "install_graylog.yml"

- include_tasks: "configure_graylog.yml"
