---

- name: "Directory should be created with correct ownership and privileges"
  file:
    path: "/etc/graylog/server"
    owner: "graylog"
    group: "graylog"
    mode: 0750

- name: "Graylog server should be configured"
  template:
    src: "graylog.server.conf.j2"
    dest: "/etc/graylog/server/server.conf"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- name: "Graylog server defaults should be configured"
  template:
    src: "graylog.server.default.j2"
    dest: "{{ graylog_server_defaults_file_path }}"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- name: "Toggle tls_key_file based on tls mode in server conf"
  lineinfile:
    path: "/etc/graylog/server/server.conf"
    regexp: '^#http_tls_key_file(.*)'
    line: 'http_tls_key_file\1'
    backrefs: yes
  when: graylog_http_enable_tls == True

- name: "Toggle tls_cert_file based on tls mode in server conf"
  lineinfile:
    path: "/etc/graylog/server/server.conf"
    regexp: '^#http_tls_cert_file(.*)'
    line: 'http_tls_cert_file\1'
    backrefs: yes
  when: graylog_http_enable_tls == True
  
- name: "Toggle http_tls_key_password based on tls mode in server conf"
  lineinfile:
    path: "/etc/graylog/server/server.conf"
    regexp: '^#http_tls_key_password(.*)'
    line: 'http_tls_key_password\1'
    backrefs: yes
  when: 
    - graylog_http_enable_tls == True
    - graylog_http_tls_key_password != ""
  
- name: "Graylog server should start after reboot"
  file:
    path: "/etc/init/graylog-server.override"
    state: "absent"

- meta: "flush_handlers"

- name: "Wait for Graylog server to startup"
  uri:
    url: "{{ graylog_http_publish_uri }}"
    status_code: 200
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: graylog_not_testing
