---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO:-centos/7}
    memory: 4096
    cpus: 1
providers:
  - name: libvirt
    type: libvirt
    driver: kvm
provisioner:
  name: ansible
verifier:
  name: ansible
